name: Build code base

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile
        run: mvn -B clean compile --file JHotDraw/pom.xml
      - name: Run tests
        run: mvn -B test --file JHotDraw/pom.xml
